[workspace]
# A separate workspace

[package]
name = "pgorm-issues-1473"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.pgorm]
path = "../../"
default-features = false
features = ["macros", "runtime-tokio-native-tls"]