[workspace]
# A separate workspace

[package]
name = "pgorm-issues-352"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
pgorm = { path = "../../", features = [ "sqlx-mysql", "runtime-async-std-native-tls" ]}
