[package]
name = "pgorm-issues-249-app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
service = { path = "../service" }
pgorm = { path = "../../../", default-features = false, features = ["macros", "tests-cfg", "sqlx-sqlite", "runtime-async-std-native-tls"] }
