[package]
name = "service"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pgorm = { path = "../../../", default-features = false }

[dev-dependencies]
pgorm = { path = "../../../", features = ["mock"] }
